#!/bin/bash
# Скрипт для деплоя с git.synch на prod сервер
# Обновляет код на prod сервере (95.163.230.61) из git.synch
# Автоматически настраивает конфигурацию для prod окружения
#
# 📖 Полная документация: см. DEPLOY_SYNCH_TO_PROD.md
# 
# ⚠️  КРИТИЧНО: Перед запуском этого скрипта выполните предварительную проверку!
#   bash rules/deploy/pre-deploy-check.sh
#   См. PRE_DEPLOY_CHECKLIST.md для полного чеклиста
#
# ⚠️  Перед деплоем убедитесь:
#   1. ✅ Все файлы присутствуют в git.synch (особенно universe-src/app, lib, components)
#   2. ✅ Локальная сборка проходит успешно (npm run build)
#   3. ✅ Нет ошибок TypeScript (npm run type-check или npx tsc --noEmit)
#   4. ✅ Нет пустых файлов
#   5. ✅ Все изменения backend закоммичены в git.synch
#
# Типичные проблемы и решения описаны в DEPLOY_SYNCH_TO_PROD.md
# ⚠️  КРИТИЧНО: После деплоя фронтенда синхронизируйте backend файлы!
#    См. BACKEND_SYNC_CHECKLIST.md

set -e

echo "=========================================="
echo "🚀 Деплой с git.synch на PROD сервер"
echo "=========================================="
echo ""

# docker-compose compatibility (prod server may only have docker-compose v1)
DOCKER_COMPOSE=""
if command -v docker-compose >/dev/null 2>&1; then
    DOCKER_COMPOSE="docker-compose"
elif docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
else
    echo "❌ Docker Compose not found (docker-compose or docker compose)."
    exit 2
fi

echo "🐳 Compose command: $DOCKER_COMPOSE"
echo ""

# Параметры
PROD_DIR="/opt/civilx-universe"
SYNCH_REPO="https://github.com/F1bonacci66/civilxuniverse.synch.git"

echo "📋 Параметры деплоя:"
echo "   Директория: $PROD_DIR"
echo "   Источник: git.synch (main branch)"
echo ""

# Переход в директорию проекта
cd "$PROD_DIR" || {
    echo "❌ Ошибка: директория $PROD_DIR не найдена"
    exit 1
}

echo "=== Проверка текущего состояния ==="
git status --short || true
echo ""

# Проверка наличия remote synch
if ! git remote | grep -q "^synch$"; then
    echo "📎 Добавление remote synch..."
    git remote add synch "$SYNCH_REPO" 2>/dev/null || true
fi

echo "📥 Получение изменений из git.synch..."
git fetch synch main

echo "🔄 Обновление кода..."
# Сохраняем текущие изменения если есть
git stash || true

# Переключаемся на main и обновляем из synch
git checkout main
git reset --hard synch/main

echo "✅ Код обновлен из git.synch"
echo ""

# Обновление конфигурации для prod
echo "⚙️  Настройка конфигурации для PROD..."

# Обновление .env для frontend (universe или universe-src)
UNIVERSE_DIR=""
if [ -d "universe" ]; then
    UNIVERSE_DIR="universe"
elif [ -d "universe-src" ]; then
    UNIVERSE_DIR="universe-src"
else
    echo "⚠️  Директория universe/universe-src не найдена, пропускаем настройку .env"
    UNIVERSE_DIR=""
fi

if [ -n "$UNIVERSE_DIR" ]; then
    if [ -f "$UNIVERSE_DIR/.env" ]; then
        echo "📝 Обновление $UNIVERSE_DIR/.env для PROD..."
        cp "$UNIVERSE_DIR/.env" "$UNIVERSE_DIR/.env.backup.$(date +%Y%m%d_%H%M%S)" || true
    fi

cat > "$UNIVERSE_DIR/.env" << 'ENVEOF'
# PROD Server Environment Variables
# Auto-generated by deploy-synch-to-prod.sh

# Next.js Public API URL (для клиентского кода в браузере)
# Используем относительный путь, чтобы работало через nginx proxy
NEXT_PUBLIC_API_URL=/api/datalab

# Internal API URL (для server-side запросов через proxy)
# Используем Docker bridge IP для доступа к backend на хосте
INTERNAL_API_URL=http://172.17.0.1:8000/api/datalab

# Docker container flag
DOCKER_CONTAINER=true

# Node environment
NODE_ENV=production

# Port
PORT=3001

# Hostname
HOSTNAME=0.0.0.0
ENVEOF

    echo "✅ $UNIVERSE_DIR/.env настроен для PROD"
    echo ""
fi

# Обновление .env для backend (если есть)
if [ -d "backend" ] && [ -f "backend/.env.example" ]; then
    echo "📝 Проверка backend/.env для PROD..."
    if [ ! -f "backend/.env" ]; then
        echo "⚠️  backend/.env не найден, создаю из примера..."
        cp backend/.env.example backend/.env
    fi
    
    # Обновляем DATABASE_URL для prod (используем host.docker.internal)
    if grep -q "DATABASE_URL" backend/.env; then
        echo "🔄 Обновление DATABASE_URL для PROD (host.docker.internal)..."
        # Сохраняем резервную копию
        cp backend/.env "backend/.env.backup.$(date +%Y%m%d_%H%M%S)" || true
        # Обновляем DATABASE_URL
        sed -i 's|DATABASE_URL=postgresql://.*@.*:5432/|DATABASE_URL=postgresql://datalab_read:StrongTempPass123!@host.docker.internal:5432/|g' backend/.env
    fi
    echo "✅ backend/.env проверен"
fi
echo ""

# Перезапуск контейнеров
echo "🔄 Перезапуск Docker контейнеров..."
# Ищем docker-compose файлы в корне или в universe/universe-src
COMPOSE_DIR=""
if [ -f "docker-compose.prod.yml" ]; then
    COMPOSE_DIR="."
elif [ -f "universe/docker-compose.prod.yml" ]; then
    COMPOSE_DIR="universe"
elif [ -f "universe-src/docker-compose.prod.yml" ]; then
    COMPOSE_DIR="universe-src"
elif [ -f "docker-compose.yml" ]; then
    COMPOSE_DIR="."
elif [ -f "universe/docker-compose.yml" ]; then
    COMPOSE_DIR="universe"
elif [ -f "universe-src/docker-compose.yml" ]; then
    COMPOSE_DIR="universe-src"
fi

if [ -n "$COMPOSE_DIR" ]; then
    cd "$COMPOSE_DIR"
    if [ -f "docker-compose.prod.yml" ]; then
        echo "📦 Используется docker-compose.prod.yml"
        # IMPORTANT: NEXT_PUBLIC_API_URL is injected at build time (Next.js).
        # Always build a local image with the correct build-arg to avoid hardcoded api.civilx.ru in the JS bundle.
        if [ -f "Dockerfile" ]; then
            echo "🔨 Build local frontend image (NEXT_PUBLIC_API_URL=/api/datalab)..."
            docker build --build-arg NEXT_PUBLIC_API_URL=/api/datalab -t civilx-universe:local -f Dockerfile .
            echo "🔄 Restart containers using local image..."
            DOCKER_IMAGE=civilx-universe:local $DOCKER_COMPOSE -f docker-compose.prod.yml down
            DOCKER_IMAGE=civilx-universe:local $DOCKER_COMPOSE -f docker-compose.prod.yml up -d
        else
            echo "⚠️  Dockerfile not found in $COMPOSE_DIR, falling back to compose (may pull from registry)"
            $DOCKER_COMPOSE -f docker-compose.prod.yml down
            $DOCKER_COMPOSE -f docker-compose.prod.yml up -d --build
        fi
        echo "✅ Контейнеры перезапущены"
    elif [ -f "docker-compose.yml" ]; then
        echo "📦 Используется docker-compose.yml"
        $DOCKER_COMPOSE down
        $DOCKER_COMPOSE up -d --build
        echo "✅ Контейнеры перезапущены"
    fi
    cd ..
else
    # Если docker-compose не найден, пересобираем и перезапускаем вручную
    echo "⚠️  docker-compose файлы не найдены, пересобираем вручную..."
    
    # Пересборка фронтенда
    if [ -d "universe-src" ] && [ -f "universe-src/Dockerfile" ]; then
        echo "🔨 Пересборка фронтенд образа..."
        cd universe-src
        docker build --build-arg NEXT_PUBLIC_API_URL=/api/datalab -t civilx-universe:local .
        if [ $? -eq 0 ]; then
            echo "✅ Образ пересобран"
            echo "🔄 Перезапуск контейнера..."
            docker stop civilx-universe 2>/dev/null || true
            docker rm civilx-universe 2>/dev/null || true
            if [ -f .env ]; then
                docker run -d --name civilx-universe --restart unless-stopped -p 3001:3001 --env-file .env civilx-universe:local
            else
                docker run -d --name civilx-universe --restart unless-stopped -p 3001:3001 civilx-universe:local
            fi
            echo "✅ Контейнер перезапущен"
        else
            echo "❌ Ошибка при пересборке образа"
        fi
        cd ..
    fi
fi

echo ""
echo "🔎 Post-deploy smoke check (strict)..."
if [ "${SKIP_SMOKE_CHECK:-0}" = "1" ]; then
    echo "⚠️  SKIP_SMOKE_CHECK=1 -> smoke check skipped"
else
    if [ -f "rules/deploy/post-deploy-smoke-check-prod.sh" ]; then
        # Requires env vars on the prod server:
        #   CIVILX_SMOKE_EMAIL, CIVILX_SMOKE_PASSWORD
        # Optional:
        #   CIVILX_BASE_URL, CIVILX_AI_MIN_ELEMENTS, CIVILX_AI_MAX_WAIT_SECONDS
        bash rules/deploy/post-deploy-smoke-check-prod.sh
    else
        echo "❌ Smoke check script not found: rules/deploy/post-deploy-smoke-check-prod.sh"
        echo "   (If you really want to proceed, rerun with SKIP_SMOKE_CHECK=1)"
        exit 1
    fi
fi

echo ""
echo "✅ Деплой завершен (smoke check passed)!"
echo ""
echo "📊 Статус контейнеров:"
docker ps --filter "name=civilx" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || true

echo ""
echo "=========================================="
echo "✅ Деплой успешно завершен!"
echo "=========================================="
echo ""
echo "🌐 Проверьте сайт: https://civilxuniverse.ru"
echo ""
echo "⚠️  ВАЖНО: После деплоя фронтенда необходимо синхронизировать backend файлы!"
echo "   См. BACKEND_SYNC_CHECKLIST.md для инструкций"
echo "   Или используйте скрипт: sync-all-backend-files.ps1"
echo ""

