#!/bin/bash
# Скрипт инициализации переменных окружения для PROD сервера
# Запускать после git pull на prod сервере (95.163.230.61)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Инициализация переменных окружения для PROD сервера ==="
echo ""

# Проверяем, существует ли .env файл
if [ -f .env ]; then
    echo "⚠️  Файл .env уже существует"
    read -p "Перезаписать? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Отменено. Используется существующий .env файл"
        exit 0
    fi
    echo "Создаю резервную копию существующего .env..."
    cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
fi

# Создаем .env файл для prod
cat > .env << 'EOF'
# PROD Server Environment Variables
# Auto-generated by init-prod-env.sh

# Next.js Public API URL (для клиентского кода в браузере)
# Используем относительный путь, чтобы работало через nginx proxy
NEXT_PUBLIC_API_URL=/api/datalab

# Internal API URL (для server-side запросов через proxy)
# Используем Docker bridge IP для доступа к backend на хосте
INTERNAL_API_URL=http://172.17.0.1:8000/api/datalab

# Docker container flag
DOCKER_CONTAINER=true

# Node environment
NODE_ENV=production

# Port
PORT=3001

# Hostname
HOSTNAME=0.0.0.0
EOF

echo "✅ .env файл создан для PROD сервера"
echo ""
echo "Содержимое .env:"
echo "---"
cat .env
echo "---"
echo ""
echo "✅ Инициализация завершена!"
echo ""
echo "Следующие шаги:"
echo "1. Проверьте содержимое .env файла"
echo "2. При необходимости отредактируйте: nano .env"
echo "3. Перезапустите контейнер: docker compose restart"

